# yaml-language-server: $schema=https://json.schemastore.org/dependabot-2.0.json
version: 2
updates:
  - directory: /
    package-ecosystem: gradle
    labels:
      - Dependency
    schedule:
      interval: weekly
      day: wednesday
      timezone: Canada/Mountain
      time: "12:00"
  - directory: /
    package-ecosystem: github-actions
    labels:
      - Dependency
    schedule:
      interval: weekly
      day: wednesday
      timezone: Canada/Mountain
      time: "12:00"
